services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
